# Generated by Django 5.1.7 on 2025-03-24 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestcotes', '0002_cours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestcotes.cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestcotes.etudiant')),
            ],
            options={
                'db_table': 'gestcotes_cote',
                'managed': True,
            },
        ),
    ]
