# Generated by Django 5.1.7 on 2025-03-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestcotes', '0003_cote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='professeur',
        ),
        migrations.AddField(
            model_name='cours',
            name='intituler',
            field=models.CharField(default='', max_length=25),
        ),
    ]
